name: Build and run C++

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
       run: sudo apt-get update && sudo apt-get install build-essential cmake -y
#      run: sudo apt-get update && sudo apt-get install build-essential cmake libglfw3-dev libopenal-dev libxcursor-dev libxinerama-dev libxrandr-dev libxi-dev libgl-dev libxxf86vm-dev -y

#    - name: Install Raylib
#      run: |
#        git clone https://github.com/raysan5/raylib.git
#        cd raylib/src
#        make PLATFORM=PLATFORM_DESKTOP
#        sudo make install

    - name: Configure with CMake
      run: cmake -S . -B build/

    - name: Build project
      run: cmake --build build/

    - name: Check binary
      run: find test
