name: iOS-ipa-build

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: write

jobs:
  build-ios:
    name: 🎉 iOS Build 🎉 
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get
        working-directory: mobile

      - run: pod repo update
        working-directory: mobile/ios

      - run: flutter build ios --no-codesign
        working-directory: mobile

      - run: mkdir Payload
        working-directory: mobile/build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: mobile/build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 client.ipa Payload
        working-directory: mobile/build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mobile/build/ios/iphoneos/client.ipa
          tag: v1.0
          overwrite: true
          body: "Ipa release"
