name: Linter C++

on:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install clang-tidy
      run: sudo apt-get update && sudo apt-get install -y clang-tidy

    - name: Configure with CMake
      run: cmake -S . -B build/

    - name: Run clang-tidy linter
      run: |
        clang-tidy \
          --fix \
          --fix-errors \
          $(find . -name '*.cpp' ! \( -path './asio/*' -o -path './build/*' \)) \
          -- -iquote./include
